### ISSUE TITLE
Doc correction

### ISSUE THREAD

**Issue by wb666greene** [bartbutenaers/node-red-contrib-multipart-stream-decoder#1]
> When we execute a HTTP request, the result will be a HTTP response containing the result data. For example every camera provides an URL that can be used to get a single snapshot image.

This is not true, I have a straight from China BESDER model that returns this from an Onvif getProfile command:
`
{
  "Manufacturer": "Technology",
  "Model": "IPC",
  "FirmwareVersion": "13.01.00.44",
  "SerialNumber": "15070713",
  "HardwareId": "Ver 2.1"
}
Getting device2 Current Profile.
{
  "token": "IPCProfilesToken0",
  "name": "MainStream",
  "snapshot": "",
  "stream": {
    "udp": "rtsp://192.168.2.92:554/onvif1",
    "http": "rtsp://192.168.2.92:554/onvif1",
    "rtsp": "rtsp://192.168.2.92:554/onvif1"
  },
 
`
Note that there is no snapshot URL.

Here is the link on Ali Express so you can avoid it:
[https://www.aliexpress.com/item/BESDER-Yoosee-IP-Camera-Wifi-1080P-960P-720P-ONVIF-Wireless-Wired-P2P-CCTV-Bullet-Outdoor-Camera/32793309300.html?spm=a2g0s.9042311.0.0.4dc54c4dFKzr6O](url)

This one sold by the same "store" has a useful subset of Onvif features but as far as I can tell only captures D1 sized snapshots.  I think the 1920x1080 rtsp stream is very good quality for the price, but it doesn't look like an overlaid timestamp will stay accurate for very long.  Another issue is it shipped with a fixed IP so it was a PITA to connect to the first time so I could enable DHCP and this could only be done from Windows as far as I could figure.
[https://www.aliexpress.com/item/BESDER-2-8mmWide-IP-Camera-1080P-960P-720P-Email-Alert-XMEye-ONVIF-P2P-Motion-Detection-RTSP/32819313586.html?spm=a2g0s.9042311.0.0.4dc54c4dFKzr6O](url)

This camera in the same price range while only 720p resolution has been very well behaved, although it may be also shipped with a fixed IP address, the documentation I downloaded seemed ambiguous. I got it from a friend who removed it from a system he was upgrading so it came to me with the fixed IP he was using,  same PITA Windows only setup.
[https://www.amazon.com/Geovision-UVS-ABL1300-1-3MP-Bullet-Camera/dp/B06XTMD2L7/ref=pd_bxgy_421_img_2?_encoding=UTF8&pd_rd_i=B06XTMD2L7&pd_rd_r=XD8KK0AC63P0VMFGFXN2&pd_rd_w=Bi3Y5&pd_rd_wg=BZAuN&psc=1&refRID=XD8KK0AC63P0VMFGFXN2](url)

**Comment by bartbutenaers** [comment]
Hi @wb666greene,

Sorry for the late reply, but seems I have missed a couple of issues from which I have received no email notifications.

Thanks for the update!  Have updated it.  Good that you mention the Onvif example, because I'm going to continue soon with my [node-red-contrib-onvif](https://github.com/bartbutenaers/node-red-contrib-onvif) node.  Then I will take into account your feedback ...

Kind regards,
Bart
