### ISSUE TITLE
Can Digest authentication be added?

### ISSUE THREAD

**Issue by Gun-neR** [bartbutenaers/node-red-contrib-multipart-stream-decoder#11]
I have been unable to get my Amcrest IP camera (IP2M-841) to work with my authorisation in this node.  The Amcrest has NO unsecured option.

**EDIT** -  I finally determined (by using the HTTP Request node and a snapshot URL) that my Amcrest uses **Digest** authentication not Basic authentication.  Is that something that can be added?

![image](https://user-images.githubusercontent.com/28169425/127250705-59c809f1-895f-45dd-a9c1-9857fb0660f7.png)

![image](https://user-images.githubusercontent.com/28169425/127250813-b1d1dca8-bfb7-476c-8169-7a60f65d2b46.png)

**Comment by bartbutenaers** [comment]
Hi @Gun-neR,
As you can see [here](https://github.com/bartbutenaers/node-red-contrib-multipart-stream-decoder/issues/5), this feature has already been requested a few times before.  I will close this issue, and answer you in that other discussion to keep things together.

**Comment by Gun-neR** [comment]
Opps, sorry.  I missed that one.  Thanks.
