### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:80

### ISSUE THREAD

**Issue by arozhankov** [bartbutenaers/node-red-contrib-multipart-stream-decoder#9]
Hello!

Can you please tell me what I need to change for normal operation?

I have "Error: connect ECONNREFUSED 127.0.0.1:80" with URL  = "http://admin:pass@IP/streaming/channels/101/preview?Resolution=640x480".

Stream works correctly in the browser.

(Hikvision cam)

**Comment by bartbutenaers** [comment]
Hi,
Could it be that your Hikvision camera only supports digest authentication?  This node currently only supports basic authentication.
Bart

**Comment by arozhankov** [comment]
> ...only supports digest authentication.....

Thank you!!
